---
# See https://pre-commit.com for more information
default_language_version:
  python: python3.10

# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: check-yaml
      # Might make sense once everything is at Python 3
      # - id: check-ast
      - id: check-added-large-files
        args:
          - '--maxkb=1024'
      - id: debug-statements
      - id: mixed-line-ending
        args:
          - '--fix=lf'
      - id: check-docstring-first
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.243'
    hooks:
      - id: ruff
        args:
          - '--fix'
  - repo: 'https://github.com/psf/black'
    rev: 23.1.0
    hooks:
      - id: black
